#!/bin/bash
# Installs (or uninstalls) ClaudePowerMode to /Applications and registers a
# LaunchAgent so it starts at every login.
#
# Usage:
#   ./install.sh                  # build, install, launch
#   ./install.sh --uninstall      # remove app, LaunchAgent, and wake sudoers rule
#   ./install.sh --enable-wake    # add narrow sudoers rule allowing passwordless pmset schedule wake
#   ./install.sh --disable-wake   # remove the sudoers rule
set -euo pipefail
cd "$(dirname "$0")"

LABEL="local.Page"
APP_SRC="Page.app"
APP_DEST="/Applications/Page.app"
BUNDLE_NAME="Page"
PLIST_PATH="$HOME/Library/LaunchAgents/$LABEL.plist"
SUDOERS_FILE="/etc/sudoers.d/claude-power-mode"
UID_NUM="$(id -u)"
USER_NAME="$(id -un)"

# Legacy install paths. The app was originally called ClaudePowerMode and
# briefly PageAI before settling on Page. We clean both up so an old menu
# bar process doesn't fight for the slot.
LEGACY_LABELS=("local.ClaudePowerMode" "local.PageAI")
LEGACY_APPS=("/Applications/ClaudePowerMode.app" "/Applications/PageAI.app")
LEGACY_BUNDLES=("ClaudePowerMode" "PageAI")

cleanup_legacy() {
    for i in "${!LEGACY_LABELS[@]}"; do
        local lbl="${LEGACY_LABELS[$i]}"
        local app="${LEGACY_APPS[$i]}"
        local bundle="${LEGACY_BUNDLES[$i]}"
        local plist="$HOME/Library/LaunchAgents/$lbl.plist"
        if launchctl list "$lbl" >/dev/null 2>&1; then
            echo "==> Stopping legacy $bundle LaunchAgent"
            launchctl bootout "gui/$UID_NUM/$lbl" 2>/dev/null || true
        fi
        pkill -f "$bundle.app/Contents/MacOS/$bundle" 2>/dev/null || true
        if [[ -f "$plist" ]]; then
            echo "==> Removing legacy LaunchAgent plist ($lbl)"
            rm -f "$plist"
        fi
        if [[ -d "$app" ]]; then
            echo "==> Removing legacy $app"
            rm -rf "$app"
        fi
    done
}

enable_wake() {
    echo "==> Installing narrow sudoers rule at $SUDOERS_FILE"
    echo "    This grants only: pmset schedule wake (and pmset schedule cancelall)"
    echo "    You'll be prompted for your admin password once."
    local tmp
    tmp="$(mktemp)"
    cat > "$tmp" <<EOF
# Generated by ClaudePowerMode install.sh
# Allow $USER_NAME to schedule system wakes without password
$USER_NAME ALL=(root) NOPASSWD: /usr/bin/pmset schedule wake *
$USER_NAME ALL=(root) NOPASSWD: /usr/bin/pmset schedule cancelall
EOF
    # Validate before installing — visudo -c rejects broken files
    if ! sudo visudo -c -f "$tmp" >/dev/null 2>&1; then
        echo "!! Sudoers fragment failed validation. Aborting."
        rm -f "$tmp"
        exit 1
    fi
    sudo install -m 0440 -o root -g wheel "$tmp" "$SUDOERS_FILE"
    rm -f "$tmp"
    echo "==> Wake permission enabled. Test with:"
    echo "    sudo -n pmset schedule wake \"$(date -v+5M '+%m/%d/%Y %H:%M:%S')\" && sudo pmset schedule cancelall"
}

disable_wake() {
    if [[ -f "$SUDOERS_FILE" ]]; then
        echo "==> Removing $SUDOERS_FILE (admin password required)"
        sudo rm -f "$SUDOERS_FILE"
    fi
    echo "Wake permission disabled."
}

uninstall() {
    echo "==> Stopping running instance"
    launchctl bootout "gui/$UID_NUM/$LABEL" 2>/dev/null || true
    pkill -f "$BUNDLE_NAME.app/Contents/MacOS/$BUNDLE_NAME" 2>/dev/null || true
    # Bootout any scheduled resume jobs as well (current + legacy labels)
    for plist in "$HOME/Library/LaunchAgents/local.Page.resume."*.plist "$HOME/Library/LaunchAgents/local.PageAI.resume."*.plist "$HOME/Library/LaunchAgents/local.ClaudePowerMode.resume."*.plist; do
        [[ -f "$plist" ]] || continue
        local_label="$(basename "$plist" .plist)"
        launchctl bootout "gui/$UID_NUM/$local_label" 2>/dev/null || true
        rm -f "$plist"
    done
    if [[ -f "$PLIST_PATH" ]]; then
        echo "==> Removing $PLIST_PATH"
        rm -f "$PLIST_PATH"
    fi
    if [[ -d "$APP_DEST" ]]; then
        echo "==> Removing $APP_DEST"
        rm -rf "$APP_DEST"
    fi
    cleanup_legacy
    if [[ -f "$SUDOERS_FILE" ]]; then
        echo "==> Removing sudoers rule (admin password required)"
        sudo rm -f "$SUDOERS_FILE"
    fi
    echo "Uninstalled."
}

case "${1:-}" in
    --uninstall) uninstall; exit 0 ;;
    --enable-wake) enable_wake; exit 0 ;;
    --disable-wake) disable_wake; exit 0 ;;
esac

echo "==> Building (always, to pick up any source changes)"
./build.sh

cleanup_legacy

echo "==> Stopping any running Page instance"
launchctl bootout "gui/$UID_NUM/$LABEL" 2>/dev/null || true
pkill -f "$BUNDLE_NAME.app/Contents/MacOS/$BUNDLE_NAME" 2>/dev/null || true
sleep 1

echo "==> Copying to $APP_DEST"
rm -rf "$APP_DEST"
cp -R "$APP_SRC" "$APP_DEST"

# Strip the quarantine attribute that macOS adds to anything copied around,
# so Gatekeeper doesn't pop "are you sure" on first launch.
xattr -dr com.apple.quarantine "$APP_DEST" 2>/dev/null || true

echo "==> Writing LaunchAgent at $PLIST_PATH"
mkdir -p "$(dirname "$PLIST_PATH")"
cat > "$PLIST_PATH" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$APP_DEST/Contents/MacOS/$BUNDLE_NAME</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>StandardOutPath</key>
    <string>$HOME/Library/Logs/Page.stdout.log</string>
    <key>StandardErrorPath</key>
    <string>$HOME/Library/Logs/Page.stderr.log</string>
</dict>
</plist>
PLIST

echo "==> Loading LaunchAgent"
launchctl bootstrap "gui/$UID_NUM" "$PLIST_PATH"

sleep 2

if pgrep -f "$BUNDLE_NAME.app/Contents/MacOS/$BUNDLE_NAME" >/dev/null; then
    echo "==> Running. Look for the icon in your menu bar (top right)."
    echo "    To uninstall:  ./install.sh --uninstall"
else
    echo "!! App did not start. Check logs:"
    echo "   tail $HOME/Library/Logs/Page.stderr.log"
    exit 1
fi
